### ISSUE TITLE
int fields are translated as float32

### ISSUE THREAD

**Issue by k1nho** [open-sauced/go-api#1]
### Type of feature

🍕 Feature

### Current behavior

The current translation of the API seems to identify ```number``` type as ```float32``` in the Go API for most of the int fields, this requires to do the manual casting to int type.  For example ```DbRepo``` model has ```Id``` field as float32. Similarly, when querying for contributors it expects ```Page```, ```Limit```, and ```Range_``` to be float32.

### Suggested solution

```float32``` needs to be ```int```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
This should now be fixed in https://github.com/open-sauced/go-api/commit/30fe67759eff958786960bb6ad2b94d00114806d

Thanks all for raising issues!!
