### ISSUE TITLE
Bug: BakeRepoDto needs to use boolean for the `wait` parameter

### ISSUE THREAD

**Issue by cecobask** [open-sauced/go-api#2]
### Describe the bug

API calls to [POST /v1/bake](https://api.opensauced.pizza/#/Pizza%20oven%20service/Bake%20a%20repository%20with%20the%20pizza%20oven%20microservice) fail with status code 400 because the go client generated the `wait` parameter as string type.

### Steps to reproduce

1. Go to https://api.opensauced.pizza/#/Pizza%20oven%20service/Bake%20a%20repository%20with%20the%20pizza%20oven%20microservice
2. Set environment to production
3. Set the request body to:
```
{
  "url": "https://github.com/open-sauced/insights",
  "wait": "false"
}
```
4. Observe the response status code to be 400
5. Set the request body to:
```
{
  "url": "https://github.com/open-sauced/insights",
  "wait": false
}
```
6. Observe the response status code to be 201

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
This should be fixed in https://github.com/open-sauced/go-api/commit/30fe67759eff958786960bb6ad2b94d00114806d
