### ISSUE TITLE
Bug: custom time type not properly (un)marshalled

### ISSUE THREAD

**Issue by cecobask** [open-sauced/go-api#3]
### Describe the bug

The following error was received:
```
parsing time "2023-08-16" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"
```

The `DateTime` type needs to implement [Marshaler](https://pkg.go.dev/encoding/json#Marshaler) in order to handle non-default time layouts such as `2023-08-16`.
The HTTP requests that the go client sends return status code `200` and valid request body. Example:
```
[
    {
        "day": "2023-08-16",
        "interval": 30,
        "all_prs": 68,
        "accepted_prs": 35,
        "spam_prs": 0
    },
    {
        "day": "2023-07-17",
        "interval": 60,
        "all_prs": 102,
        "accepted_prs": 57,
        "spam_prs": 0
    }
]
```

### Steps to reproduce

1. Invoke `PullRequestsServiceAPI.GetPullRequestInsights`
2. Observe the reported error as a result of decoding json

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by cecobask** [comment]
Hello @jpmcb,
Please, review these changes when you get the chance.
Thank you!

**Comment by jpmcb** [comment]
Close by https://github.com/open-sauced/go-api/commit/8a8b1fa31f604a22f143080193bc4f9792eb0b57
